UPDATE items
SET PVP = 1
WHERE name LIKE 'Relentless Gladiator%' 
OR name LIKE 'Wrathful Gladiator%'
OR name LIKE 'Furious Gladiator%'
OR name LIKE 'Deadly Gladiator%'
OR name LIKE 'Hateful Gladiator%'
OR name LIKE 'Savage Gladiator%'
OR name LIKE 'Medallion of the Alliance%'
OR name LIKE 'Medallion of the Horde%'
OR name LIKE 'Talisman of the Alliance%'
OR name LIKE 'Insignia of the Alliance%'
OR name LIKE 'Talisman of the Horde%'
OR name LIKE 'Insignia of the Horde%'
OR name LIKE 'Sergeant''s Heavy Cloak%'
OR name LIKE 'General''s Dreadweave%'
OR name LIKE 'General''s Silk%'
OR name LIKE 'General''s Mooncloth%'
OR name LIKE 'General''s Dragonhide%'
OR name LIKE 'General''s Leather%'
OR name LIKE 'General''s Wyrmhide%'
OR name LIKE 'General''s Kodohide%'
OR name LIKE 'General''s Chain%'
OR name LIKE 'General''s Mail%'
OR name LIKE 'General''s Ringmail%'
OR name LIKE 'General''s Linked%'
OR name LIKE 'General''s Plate%'
OR name LIKE 'General''s Scaled%'
OR name LIKE 'General''s Ornamented%'
OR name LIKE 'General''s Lamellar%'
OR name LIKE 'Pendant of Dominance%'
OR name LIKE 'Band of Triumph'
OR name LIKE 'Band of Dominance'
OR name LIKE 'Gladiator''s Silk%'
OR name LIKE 'Battlemaster''s Vivacity'
OR name LIKE 'Battlemaster''s Ruination'
OR name LIKE 'Battlemaster''s Rage'
OR name LIKE 'Battlemaster''s Precision'
OR name LIKE 'Battlemaster''s Fury'
OR name LIKE 'Battlemaster''s Resolve'
OR name LIKE 'Battlemaster''s Courage'
OR name LIKE 'Battlemaster''s Celerity'
OR name LIKE 'Battlemaster''s Aggression'
OR name LIKE 'Battlemaster''s Perseverance'
OR name LIKE 'Battlemaster''s Determination'
OR name LIKE 'Battlemaster''s Depravity'
OR name LIKE 'Battlemaster''s Cruelty'
OR name LIKE 'Battlemaster''s Audacity'
OR name LIKE 'Battlemaster''s Alacrity'
OR name LIKE 'Battlemaster''s Hostility'
OR name LIKE 'Battlemaster''s Accuracy'
OR name LIKE 'Battlemaster''s Avidity'
OR name LIKE 'Battlemaster''s Conviction'
OR name LIKE 'Battlemaster''s Bravery'
OR name LIKE 'Titan-Forged %'
OR name LIKE 'Anvil of Titans%'
OR name LIKE 'Flow of Knowledge%'
OR name LIKE 'Platinum Disks of%'
OR name LIKE 'Exquisite Sunderseer Mantle%'
OR name LIKE 'Exceptional Stormshroud Shoulders%'
OR name LIKE 'Lasting Feralheart Spaulders%'
OR name LIKE 'Prized Beastmaster''s Mantle%'
OR name LIKE 'Aged Pauldrons of The Five Thunders%'
OR name LIKE 'Strengthened Stockade Pauldrons%'
OR name LIKE 'Pristine Lightforge Spaulders%'
OR name LIKE 'Sharpened Scarlet Kris%'
OR name LIKE 'Battleworn Thrash Blade%'
OR name LIKE 'The Blessed Hammer of Grace%'
OR name LIKE 'Reforged Truesilver Champion%'
OR name LIKE 'Grand Staff of Jordan%'
OR name LIKE 'Upgraded Dwarven Hand Cannon%'